[build]
  publish = "public"
  functions = "netlify/functions"
  node_version = "18"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
